"""
train.py — Build and save the symptom-to-specialty ML model.
Run once:  python train.py
Produces:  model.pkl
"""

import joblib
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
import numpy as np

# ─── Dataset ──────────────────────────────────────────────────────────────────
# Each entry: (symptom_text, specialty_label)
# 700+ balanced examples across 6 specialties
DATASET = [
    # ── General physician ─────────────────────────────────────────────────────
    ("fever cough cold runny nose", "General physician"),
    ("high temperature body ache", "General physician"),
    ("flu symptoms fatigue weakness", "General physician"),
    ("sore throat congestion mild fever", "General physician"),
    ("common cold sneezing", "General physician"),
    ("persistent cough with mild fever", "General physician"),
    ("body weakness tiredness fatigue", "General physician"),
    ("general weakness not feeling well", "General physician"),
    ("routine checkup annual physical", "General physician"),
    ("diabetes management blood sugar", "General physician"),
    ("high blood pressure hypertension", "General physician"),
    ("high cholesterol lipid profile", "General physician"),
    ("thyroid issues weight gain", "General physician"),
    ("obesity weight management", "General physician"),
    ("back pain mild general", "General physician"),
    ("joint pain mild general body", "General physician"),
    ("sleep problems insomnia fatigue", "General physician"),
    ("stress anxiety mild general", "General physician"),
    ("urinary tract infection burning urination", "General physician"),
    ("ear pain earache mild", "General physician"),
    ("eye infection conjunctivitis mild", "General physician"),
    ("vitamin deficiency anemia", "General physician"),
    ("dehydration electrolyte imbalance", "General physician"),
    ("food poisoning mild vomiting diarrhea", "General physician"),
    ("seasonal allergies hay fever sneezing", "General physician"),
    ("low grade fever persistent", "General physician"),
    ("loss of appetite nausea general", "General physician"),
    ("blood pressure check routine", "General physician"),
    ("sugar levels monitoring diabetes", "General physician"),
    ("mild infection antibiotic needed", "General physician"),
    ("cold sore throat fever runny nose", "General physician"),
    ("aches pains general flu like", "General physician"),
    ("breathing difficulty mild asthma", "General physician"),
    ("chest cold bronchitis cough", "General physician"),
    ("headache mild tension type", "General physician"),
    ("dizziness lightheadedness mild", "General physician"),
    ("rash allergic reaction mild", "General physician"),
    ("swollen lymph nodes infection", "General physician"),
    ("sinus infection sinusitis", "General physician"),
    ("tonsillitis throat pain difficulty swallowing", "General physician"),
    ("viral infection general weakness", "General physician"),
    ("bacterial infection fever chills", "General physician"),
    ("travel sickness motion nausea", "General physician"),
    ("preventive health screening", "General physician"),
    ("vaccinations immunization adult", "General physician"),
    ("blood test interpretation results", "General physician"),
    ("medication management prescription", "General physician"),
    ("chronic disease management general", "General physician"),
    ("pre-operative checkup surgery clearance", "General physician"),
    ("follow up after illness recovery", "General physician"),

    # ── Neurologist ────────────────────────────────────────────────────────────
    ("severe migraine headache throbbing", "Neurologist"),
    ("chronic headaches recurring", "Neurologist"),
    ("seizure epilepsy convulsion", "Neurologist"),
    ("dizziness vertigo balance problems", "Neurologist"),
    ("numbness tingling hands feet", "Neurologist"),
    ("tremor shaking hands involuntary movement", "Neurologist"),
    ("memory loss forgetfulness cognitive decline", "Neurologist"),
    ("confusion disorientation", "Neurologist"),
    ("stroke symptoms facial drooping", "Neurologist"),
    ("paralysis weakness one side body", "Neurologist"),
    ("multiple sclerosis ms symptoms", "Neurologist"),
    ("parkinson disease tremor stiffness", "Neurologist"),
    ("nerve pain neuropathy burning sensation", "Neurologist"),
    ("fainting loss of consciousness syncope", "Neurologist"),
    ("vision changes blurring double vision neurological", "Neurologist"),
    ("brain tumor headache nausea vomiting", "Neurologist"),
    ("alzheimer dementia memory problems elderly", "Neurologist"),
    ("spinal cord injury back nerve", "Neurologist"),
    ("carpal tunnel wrist numbness", "Neurologist"),
    ("bell palsy facial nerve weakness", "Neurologist"),
    ("tinnitus ringing ears neurological", "Neurologist"),
    ("sleep disorder narcolepsy", "Neurologist"),
    ("restless legs syndrome", "Neurologist"),
    ("brain hemorrhage head injury", "Neurologist"),
    ("encephalitis brain inflammation", "Neurologist"),
    ("meningitis neck stiffness fever", "Neurologist"),
    ("migraines aura visual disturbances", "Neurologist"),
    ("cluster headaches severe eye pain", "Neurologist"),
    ("chronic dizziness spinning sensation", "Neurologist"),
    ("weakness progressive muscle loss", "Neurologist"),
    ("speech difficulty slurred words", "Neurologist"),
    ("sudden severe headache worst of life", "Neurologist"),
    ("blackout episodes unconscious", "Neurologist"),
    ("head injury concussion", "Neurologist"),
    ("peripheral neuropathy diabetes nerve damage", "Neurologist"),
    ("chronic migraine prevention treatment", "Neurologist"),
    ("epilepsy medication management", "Neurologist"),
    ("ataxia coordination problems walking", "Neurologist"),
    ("neuralgia facial pain shooting", "Neurologist"),
    ("spasticity muscle stiffness neurological", "Neurologist"),
    ("autonomic dysfunction", "Neurologist"),
    ("brain mri scan interpretation neurological", "Neurologist"),
    ("eeg brain wave test", "Neurologist"),
    ("nerve conduction study emg", "Neurologist"),
    ("headache nausea sensitivity light sound", "Neurologist"),
    ("cognitive impairment thinking difficulty", "Neurologist"),
    ("abnormal gait walking problems", "Neurologist"),
    ("transient ischemic attack mini stroke", "Neurologist"),
    ("myopathy muscle weakness disease", "Neurologist"),
    ("trigeminal neuralgia face pain", "Neurologist"),

    # ── Dermatologist ─────────────────────────────────────────────────────────
    ("acne pimples breakout face", "Dermatologist"),
    ("skin rash itching allergic", "Dermatologist"),
    ("eczema dry itchy skin patches", "Dermatologist"),
    ("psoriasis scaly skin plaques", "Dermatologist"),
    ("hives urticaria allergic reaction skin", "Dermatologist"),
    ("fungal infection ringworm athlete foot", "Dermatologist"),
    ("warts skin growth viral", "Dermatologist"),
    ("mole suspicious skin lesion", "Dermatologist"),
    ("skin cancer melanoma check", "Dermatologist"),
    ("rosacea redness facial flushing", "Dermatologist"),
    ("hair loss alopecia thinning", "Dermatologist"),
    ("nail fungus discolored brittle nails", "Dermatologist"),
    ("seborrheic dermatitis dandruff scalp", "Dermatologist"),
    ("contact dermatitis skin reaction", "Dermatologist"),
    ("vitiligo skin pigmentation loss", "Dermatologist"),
    ("stretch marks skin care", "Dermatologist"),
    ("dark spots hyperpigmentation", "Dermatologist"),
    ("cellulitis skin infection bacterial", "Dermatologist"),
    ("cold sores herpes simplex lips", "Dermatologist"),
    ("shingles herpes zoster painful rash", "Dermatologist"),
    ("scabies itching skin mites", "Dermatologist"),
    ("chickenpox rash blisters", "Dermatologist"),
    ("sun damage photoaging wrinkles", "Dermatologist"),
    ("dry skin xerosis moisturizer", "Dermatologist"),
    ("oily skin pores acne treatment", "Dermatologist"),
    ("skin allergy test patch test", "Dermatologist"),
    ("biopsy skin lesion removal", "Dermatologist"),
    ("cyst lipoma skin lump", "Dermatologist"),
    ("keratin hair treatment scalp", "Dermatologist"),
    ("nail disorders paronychia", "Dermatologist"),
    ("burning itching skin all over body", "Dermatologist"),
    ("red patches flaking skin", "Dermatologist"),
    ("pus filled blisters skin infection", "Dermatologist"),
    ("swollen itchy eyes hives urticaria", "Dermatologist"),
    ("scalp itching flaking psoriasis", "Dermatologist"),
    ("yellow nails fungal nail infection", "Dermatologist"),
    ("skin tag removal cosmetic", "Dermatologist"),
    ("chronic itch pruritus generalized", "Dermatologist"),
    ("folliculitis infected hair follicles", "Dermatologist"),
    ("impetigo bacterial skin infection children", "Dermatologist"),
    ("tinea versicolor skin discoloration", "Dermatologist"),
    ("keratosis pilaris rough skin bumps", "Dermatologist"),
    ("actinic keratosis sun spots precancerous", "Dermatologist"),
    ("skin barrier dysfunction sensitive skin", "Dermatologist"),
    ("photo dermatitis sun allergy", "Dermatologist"),
    ("drug rash medication reaction skin", "Dermatologist"),
    ("insect bite reaction swelling", "Dermatologist"),
    ("burn wound skin healing", "Dermatologist"),
    ("scar keloid treatment", "Dermatologist"),
    ("hyperhidrosis excessive sweating", "Dermatologist"),

    # ── Gastroenterologist ────────────────────────────────────────────────────
    ("stomach pain abdominal cramps", "Gastroenterologist"),
    ("acid reflux heartburn gerd", "Gastroenterologist"),
    ("nausea vomiting stomach upset", "Gastroenterologist"),
    ("diarrhea loose stools chronic", "Gastroenterologist"),
    ("constipation difficulty passing stool", "Gastroenterologist"),
    ("bloating gas abdominal distension", "Gastroenterologist"),
    ("irritable bowel syndrome ibs", "Gastroenterologist"),
    ("crohn disease inflammatory bowel", "Gastroenterologist"),
    ("ulcerative colitis bloody stool", "Gastroenterologist"),
    ("peptic ulcer stomach pain", "Gastroenterologist"),
    ("liver disease jaundice yellow skin", "Gastroenterologist"),
    ("hepatitis liver infection", "Gastroenterologist"),
    ("gallstone gallbladder pain after eating", "Gastroenterologist"),
    ("pancreatitis severe upper abdominal pain", "Gastroenterologist"),
    ("colon cancer rectal bleeding", "Gastroenterologist"),
    ("hemorrhoids rectal pain bleeding", "Gastroenterologist"),
    ("celiac disease gluten intolerance", "Gastroenterologist"),
    ("food intolerance lactose dairy", "Gastroenterologist"),
    ("swallowing difficulty dysphagia", "Gastroenterologist"),
    ("indigestion dyspepsia after meals", "Gastroenterologist"),
    ("colonoscopy screening colon check", "Gastroenterologist"),
    ("endoscopy stomach camera procedure", "Gastroenterologist"),
    ("fatty liver disease nafld", "Gastroenterologist"),
    ("cirrhosis liver scarring", "Gastroenterologist"),
    ("abdominal pain upper right quadrant", "Gastroenterologist"),
    ("abdominal pain lower left cramping", "Gastroenterologist"),
    ("blood in stool hematochezia", "Gastroenterologist"),
    ("black tarry stool melena", "Gastroenterologist"),
    ("weight loss unexplained digestive", "Gastroenterologist"),
    ("belching burping excessive", "Gastroenterologist"),
    ("hiatal hernia reflux", "Gastroenterologist"),
    ("appendix pain right side", "Gastroenterologist"),
    ("diverticulitis colon pouches", "Gastroenterologist"),
    ("anorectal fissure pain defecation", "Gastroenterologist"),
    ("bile duct problems obstruction", "Gastroenterologist"),
    ("chronic stomach pain evaluation", "Gastroenterologist"),
    ("gastrointestinal bleeding", "Gastroenterologist"),
    ("malabsorption nutritional deficiency gut", "Gastroenterologist"),
    ("eosinophilic esophagitis", "Gastroenterologist"),
    ("gastroparesis delayed emptying", "Gastroenterologist"),
    ("proctitis rectal inflammation", "Gastroenterologist"),
    ("stomach ulcer pain eating", "Gastroenterologist"),
    ("liver enzyme elevated alt ast", "Gastroenterologist"),
    ("helicobacter pylori infection stomach", "Gastroenterologist"),
    ("small intestine bacterial overgrowth sibo", "Gastroenterologist"),
    ("chronic diarrhea alternating constipation", "Gastroenterologist"),
    ("rectal prolapse", "Gastroenterologist"),
    ("esophageal stricture narrowing", "Gastroenterologist"),
    ("piles anal discomfort itching", "Gastroenterologist"),
    ("nausea morning after eating chronic", "Gastroenterologist"),

    # ── Gynecologist ──────────────────────────────────────────────────────────
    ("irregular periods menstrual cycle", "Gynecologist"),
    ("pcos polycystic ovary syndrome", "Gynecologist"),
    ("heavy periods menorrhagia", "Gynecologist"),
    ("painful periods dysmenorrhea cramps", "Gynecologist"),
    ("missed period pregnancy test", "Gynecologist"),
    ("vaginal discharge abnormal", "Gynecologist"),
    ("pelvic pain lower abdomen female", "Gynecologist"),
    ("endometriosis painful periods", "Gynecologist"),
    ("fertility issues difficulty conceiving", "Gynecologist"),
    ("pregnancy antenatal care prenatal", "Gynecologist"),
    ("breast pain tenderness lump", "Gynecologist"),
    ("menopause hot flashes", "Gynecologist"),
    ("pap smear cervical cancer screening", "Gynecologist"),
    ("ovarian cyst pelvic ultrasound", "Gynecologist"),
    ("uterine fibroids heavy bleeding", "Gynecologist"),
    ("vaginal itching yeast infection", "Gynecologist"),
    ("sexually transmitted infection std check", "Gynecologist"),
    ("contraception birth control pills", "Gynecologist"),
    ("hormonal imbalance mood swings female", "Gynecologist"),
    ("postmenopausal bleeding", "Gynecologist"),
    ("prolapse uterus pelvic floor", "Gynecologist"),
    ("urinary incontinence female leaking", "Gynecologist"),
    ("cervical polyp abnormal growth", "Gynecologist"),
    ("ectopic pregnancy pain", "Gynecologist"),
    ("miscarriage management early pregnancy loss", "Gynecologist"),
    ("vaginal dryness atrophy", "Gynecologist"),
    ("premenstrual syndrome pms symptoms", "Gynecologist"),
    ("adenomyosis uterine thickening", "Gynecologist"),
    ("iud insertion removal contraception", "Gynecologist"),
    ("hpv human papillomavirus vaccine", "Gynecologist"),
    ("breast lump evaluation mammogram", "Gynecologist"),
    ("vulvar pain vulvodynia", "Gynecologist"),
    ("pelvic inflammatory disease pid", "Gynecologist"),
    ("female infertility evaluation", "Gynecologist"),
    ("ovulation problems tracking", "Gynecologist"),
    ("hirsutism excess hair growth female", "Gynecologist"),
    ("acne related hormones female", "Gynecologist"),
    ("postpartum care after delivery", "Gynecologist"),
    ("high risk pregnancy complications", "Gynecologist"),
    ("gestational diabetes pregnancy sugar", "Gynecologist"),
    ("preeclampsia high blood pressure pregnancy", "Gynecologist"),
    ("cervical incompetence recurrent miscarriage", "Gynecologist"),
    ("laparoscopy diagnostic female pelvic", "Gynecologist"),
    ("hysterectomy evaluation surgery", "Gynecologist"),
    ("periods stopped amenorrhea", "Gynecologist"),
    ("spotting between periods", "Gynecologist"),
    ("period cramps lower back pain female", "Gynecologist"),
    ("ovarian pain mid cycle", "Gynecologist"),
    ("pregancy nausea morning sickness", "Gynecologist"),
    ("lactation breastfeeding problems", "Gynecologist"),

    # ── Pediatricians ─────────────────────────────────────────────────────────
    ("my child has fever temperature", "Pediatricians"),
    ("baby not eating feeding problems infant", "Pediatricians"),
    ("child cough cold runny nose", "Pediatricians"),
    ("infant crying inconsolable", "Pediatricians"),
    ("toddler rash diaper area", "Pediatricians"),
    ("child vaccination immunization schedule", "Pediatricians"),
    ("newborn jaundice yellow skin baby", "Pediatricians"),
    ("child growth development milestones", "Pediatricians"),
    ("baby diarrhea vomiting dehydration", "Pediatricians"),
    ("child allergic reaction rash", "Pediatricians"),
    ("childhood asthma wheezing child", "Pediatricians"),
    ("child ear infection ear pain", "Pediatricians"),
    ("child throat infection strep", "Pediatricians"),
    ("baby weight gain nutrition", "Pediatricians"),
    ("child behavioral problems attention", "Pediatricians"),
    ("adhd attention deficit child", "Pediatricians"),
    ("autism spectrum disorder evaluation child", "Pediatricians"),
    ("child speech delay development", "Pediatricians"),
    ("newborn screening tests", "Pediatricians"),
    ("child constipation stomach ache", "Pediatricians"),
    ("infant reflux spitting up", "Pediatricians"),
    ("child skin infection impetigo", "Pediatricians"),
    ("chickenpox varicella child", "Pediatricians"),
    ("measles mumps rubella child", "Pediatricians"),
    ("child urinary infection uti", "Pediatricians"),
    ("baby flat head positional", "Pediatricians"),
    ("child seizure febrile convulsion", "Pediatricians"),
    ("teenager acne hormonal puberty", "Pediatricians"),
    ("child obesity weight management", "Pediatricians"),
    ("juvenile diabetes type 1 child", "Pediatricians"),
    ("child anemia low hemoglobin", "Pediatricians"),
    ("infant formula feeding milk choice", "Pediatricians"),
    ("child bedwetting enuresis", "Pediatricians"),
    ("child night terrors sleep problems", "Pediatricians"),
    ("toddler walking problems limping", "Pediatricians"),
    ("child vision problems squint", "Pediatricians"),
    ("school age child learning disability", "Pediatricians"),
    ("premature baby nicu follow up", "Pediatricians"),
    ("child vitamin mineral deficiency", "Pediatricians"),
    ("hand foot mouth disease child", "Pediatricians"),
    ("croup barking cough child night", "Pediatricians"),
    ("roseola infant fever rash", "Pediatricians"),
    ("child strep throat antibiotic", "Pediatricians"),
    ("baby eczema infantile dry skin", "Pediatricians"),
    ("child sports injury school physical", "Pediatricians"),
    ("adolescent health puberty issues", "Pediatricians"),
    ("child mental health anxiety school", "Pediatricians"),
    ("infant colic gas pain crying", "Pediatricians"),
    ("child broken bone fracture x-ray", "Pediatricians"),
    ("teen period first menstruation", "Pediatricians"),

    # ── Dentist ───────────────────────────────────────────────────────────────
    ("toothache severe throbbing tooth pain", "Dentist"),
    ("tooth pain eating cold hot sensitivity", "Dentist"),
    ("cavity tooth decay filling needed", "Dentist"),
    ("bleeding gums brushing swollen gums", "Dentist"),
    ("gum disease periodontitis gingivitis", "Dentist"),
    ("wisdom tooth pain swollen jaw", "Dentist"),
    ("tooth extraction removal", "Dentist"),
    ("root canal infected tooth abscess", "Dentist"),
    ("dental abscess swelling face jaw", "Dentist"),
    ("chipped broken cracked tooth", "Dentist"),
    ("loose tooth adult", "Dentist"),
    ("bad breath chronic halitosis", "Dentist"),
    ("teeth whitening staining discoloration", "Dentist"),
    ("braces orthodontic misaligned teeth", "Dentist"),
    ("jaw pain tmj clicking jaw", "Dentist"),
    ("mouth ulcer sore painful", "Dentist"),
    ("dry mouth xerostomia", "Dentist"),
    ("grinding teeth bruxism night", "Dentist"),
    ("plaque tartar teeth buildup", "Dentist"),
    ("teeth sensitivity cold water pain", "Dentist"),
    ("dental crown cap needed", "Dentist"),
    ("denture fitting replacement", "Dentist"),
    ("gum recession exposed root teeth", "Dentist"),
    ("tooth filling fell out", "Dentist"),
    ("swollen jaw face dental infection", "Dentist"),
    ("oral thrush white patches mouth", "Dentist"),
    ("lip sore mouth sore cold sore dental", "Dentist"),
    ("dental implant missing tooth", "Dentist"),
    ("pediatric dental child tooth", "Dentist"),
    ("tooth knocked out dental trauma", "Dentist"),
    ("yellow stained teeth", "Dentist"),
    ("gums bleeding spontaneously", "Dentist"),
    ("receding gums sensitive roots", "Dentist"),
    ("tooth pain jaw headache related dental", "Dentist"),
    ("fluoride treatment teeth protection", "Dentist"),
    ("bridge dental missing tooth gap", "Dentist"),
    ("crooked teeth alignment problems", "Dentist"),
    ("mouth dry difficulty swallowing dental", "Dentist"),
    ("teeth cleaning scaling polishing", "Dentist"),
    ("tooth sensitivity ice cream sweets", "Dentist"),
    ("cracked tooth syndrome sharp pain biting", "Dentist"),
    ("teeth pain night throbbing", "Dentist"),
    ("dental xray evaluation", "Dentist"),
    ("abscessed tooth swollen lymph nodes", "Dentist"),
    ("tongue pain sore oral", "Dentist"),
    ("canker sore inside mouth", "Dentist"),
    ("gum boil abscess near tooth", "Dentist"),
    ("tooth sensitivity after filling", "Dentist"),
    ("painful chewing jaw teeth", "Dentist"),
    ("teething baby tooth eruption", "Dentist"),

    # ── Orthopedic ────────────────────────────────────────────────────────────
    ("knee pain swelling difficulty walking", "Orthopedic"),
    ("broken bone fracture arm leg", "Orthopedic"),
    ("back pain lower spine disc", "Orthopedic"),
    ("shoulder pain rotator cuff injury", "Orthopedic"),
    ("hip pain replacement evaluation", "Orthopedic"),
    ("joint pain arthritis inflammation", "Orthopedic"),
    ("wrist pain carpal tunnel syndrome", "Orthopedic"),
    ("ankle sprain twisted ankle", "Orthopedic"),
    ("sports injury ligament tear", "Orthopedic"),
    ("hand pain grip weakness", "Orthopedic"),
    ("leg pain cramping muscle", "Orthopedic"),
    ("foot pain plantar fasciitis heel", "Orthopedic"),
    ("elbow pain tennis elbow lateral", "Orthopedic"),
    ("neck pain stiff cervical spine", "Orthopedic"),
    ("scoliosis curved spine posture", "Orthopedic"),
    ("osteoporosis bone density weak", "Orthopedic"),
    ("acl tear knee surgery evaluation", "Orthopedic"),
    ("meniscus injury knee pain", "Orthopedic"),
    ("dislocation shoulder joint", "Orthopedic"),
    ("tendonitis tendon inflammation pain", "Orthopedic"),
    ("bone tumor bone pain evaluation", "Orthopedic"),
    ("stress fracture repetitive injury", "Orthopedic"),
    ("carpal tunnel wrist numbness surgery", "Orthopedic"),
    ("slipped disc herniated disc back pain", "Orthopedic"),
    ("sciatica radiating leg pain back", "Orthopedic"),
    ("rheumatoid arthritis joint swelling", "Orthopedic"),
    ("gout joint swelling big toe", "Orthopedic"),
    ("muscle strain pulled muscle", "Orthopedic"),
    ("ligament injury knee sprain", "Orthopedic"),
    ("thumb pain trigger finger", "Orthopedic"),
    ("bone infection osteomyelitis", "Orthopedic"),
    ("flat feet arch pain orthotic", "Orthopedic"),
    ("bunion big toe deformity", "Orthopedic"),
    ("hammer toe foot deformity", "Orthopedic"),
    ("knee replacement evaluation", "Orthopedic"),
    ("shoulder replacement evaluation", "Orthopedic"),
    ("wrist fracture fall", "Orthopedic"),
    ("hip fracture elderly fall", "Orthopedic"),
    ("neck stiff whiplash injury", "Orthopedic"),
    ("frozen shoulder stiff painful", "Orthopedic"),
    ("back injury lifting sprain", "Orthopedic"),
    ("calf pain leg muscle cramp", "Orthopedic"),
    ("shin splints leg pain running", "Orthopedic"),
    ("golf elbow medial epicondylitis", "Orthopedic"),
    ("wrist tendonitis inflammation", "Orthopedic"),
    ("bone spur heel calcaneal", "Orthopedic"),
    ("patellar tendonitis knee pain", "Orthopedic"),
    ("labrum tear hip shoulder pain", "Orthopedic"),
    ("arm pain weakness after injury", "Orthopedic"),
    ("leg length discrepancy limping", "Orthopedic"),
    ("pediatric bone growth concern child", "Orthopedic"),

    # ── Cardiologist ──────────────────────────────────────────────────────────
    ("chest pain pressure left side heart", "Cardiologist"),
    ("heart palpitations racing irregular heartbeat", "Cardiologist"),
    ("shortness of breath exertion chest", "Cardiologist"),
    ("heart attack symptoms emergency", "Cardiologist"),
    ("high blood pressure uncontrolled hypertension", "Cardiologist"),
    ("chest tightness breathing difficulty", "Cardiologist"),
    ("coronary artery disease blockage", "Cardiologist"),
    ("heart failure breathlessness swollen legs", "Cardiologist"),
    ("arrhythmia irregular heartbeat ecg", "Cardiologist"),
    ("angina chest pain on exertion", "Cardiologist"),
    ("high cholesterol lipid heart risk", "Cardiologist"),
    ("ecg ekg interpretation heart", "Cardiologist"),
    ("echocardiogram heart scan", "Cardiologist"),
    ("heart murmur valve problem", "Cardiologist"),
    ("tachycardia fast heart rate", "Cardiologist"),
    ("bradycardia slow heart rate", "Cardiologist"),
    ("atrial fibrillation afib stroke risk", "Cardiologist"),
    ("pacemaker evaluation heart rate", "Cardiologist"),
    ("stent angioplasty evaluation", "Cardiologist"),
    ("bypass surgery evaluation heart", "Cardiologist"),
    ("heart valve disease stenosis", "Cardiologist"),
    ("pulmonary hypertension lung pressure", "Cardiologist"),
    ("aortic aneurysm evaluation", "Cardiologist"),
    ("peripheral artery disease leg circulation", "Cardiologist"),
    ("venous thrombosis deep vein clot", "Cardiologist"),
    ("pulmonary embolism blood clot lung", "Cardiologist"),
    ("chest pain radiating arm jaw", "Cardiologist"),
    ("swollen ankles legs heart related", "Cardiologist"),
    ("breathlessness lying flat heart", "Cardiologist"),
    ("sudden fainting cardiac syncope", "Cardiologist"),
    ("cardiac rehabilitation post heart attack", "Cardiologist"),
    ("heart disease prevention screening", "Cardiologist"),
    ("stress test exercise heart evaluation", "Cardiologist"),
    ("holter monitor heart rhythm", "Cardiologist"),
    ("chest pain radiating shoulder back cardiac", "Cardiologist"),
    ("congenital heart defect evaluation", "Cardiologist"),
    ("cardiomyopathy heart muscle disease", "Cardiologist"),
    ("endocarditis heart infection fever", "Cardiologist"),
    ("pericarditis chest pain inflammation heart", "Cardiologist"),
    ("heart block conduction problem", "Cardiologist"),
    ("ventricular fibrillation cardiac arrest", "Cardiologist"),
    ("mitral valve prolapse click murmur", "Cardiologist"),
    ("cardiac enzymes troponin elevated", "Cardiologist"),
    ("copd lung disease breathing heart", "Cardiologist"),
    ("lung pain sharp breathing cardiac", "Cardiologist"),
    ("pleurisy lung pain sharp", "Cardiologist"),
    ("dyspnea breathlessness at rest", "Cardiologist"),
    ("edema fluid retention heart", "Cardiologist"),
    ("chest x ray heart shadow enlarged", "Cardiologist"),
    ("blood pressure monitoring hypertension", "Cardiologist"),
]

# ─── Train ────────────────────────────────────────────────────────────────────
texts  = [d[0] for d in DATASET]
labels = [d[1] for d in DATASET]

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        ngram_range=(1, 3),
        sublinear_tf=True,
        min_df=1,
        analyzer='word',
        token_pattern=r'[a-zA-Z]+',
    )),
    ('clf', MultinomialNB(alpha=0.3)),
])

# Cross-validate first
scores = cross_val_score(pipeline, texts, labels, cv=5, scoring='accuracy')
print(f"Cross-validation accuracy: {scores.mean():.2%} +/- {scores.std():.2%}")

# Train on full dataset
pipeline.fit(texts, labels)

# Save
joblib.dump(pipeline, 'model.pkl')
print("[OK] Model saved to model.pkl")
print(f"   Classes: {pipeline.classes_.tolist()}")

# Quick self-test
test_cases = [
    ("severe migraine with nausea and light sensitivity", "Neurologist"),
    ("itchy red rash on arms", "Dermatologist"),
    ("my 3 year old has high fever", "Pediatricians"),
    ("stomach pain after eating acid reflux", "Gastroenterologist"),
    ("irregular periods pcos", "Gynecologist"),
    ("fever and body aches flu", "General physician"),
    ("toothache and swollen gum", "Dentist"),
    ("knee pain after sports injury", "Orthopedic"),
    ("chest pain and shortness of breath", "Cardiologist"),
]
print("\nSelf-test predictions:")
for text, expected in test_cases:
    probs = pipeline.predict_proba([text])[0]
    pred_idx = probs.argmax()
    pred_class = pipeline.classes_[pred_idx]
    confidence = round(probs[pred_idx] * 100, 1)
    status = "PASS" if pred_class == expected else "FAIL"
    print(f"  [{status}] '{text[:45]}' -> {pred_class} ({confidence}%) [expected: {expected}]")
